### ISSUE TITLE
Review the operator documentation in the README and fix it

### ISSUE THREAD

**Issue by axch** [probcomp/probcomp-stack#13]
Particularly, I'm not sure I got the `--stack-name` parameters to `aws cloudformation` right.

**Comment by riastradh-probcomp** [comment]
Stack name issue fixed in cf4b45e779458d065e0c459619573d3764e87962.

**Comment by riastradh-probcomp** [comment]
Other updates done.  Someone else should run through this to make sure it works for not-me.

**Comment by axch** [comment]
I am satisfied that the instructions work.
