### ISSUE TITLE
Pin availability zone choice?

### ISSUE THREAD

**Issue by axch** [probcomp/probcomp-stack#16]
Tried to create a stack and got "your chosen availability zone (us-east-1a) does not support your chosen instance type (c3.8xlarge)".  I notice that all our other instances are not in us-east-1a, including a bunch of t2.micros I successfully created.  Does it choose the zone randomly?  How can this be fixed?

**Comment by axch** [comment]
Workaround: Just delete the stack and create it again.  Apparently this time it picked a different availability zone and succeeded.

**Comment by riastradh-probcomp** [comment]
> Date: Fri, 26 May 2017 06:20:06 -0700
> From: axch <notifications@github.com>
> 
> Tried to create a stack and got "your chosen availability zone
> (us-east-1a) does not support your chosen instance type
> (c3.8xlarge)".  I notice that all our other instances are not in
> us-east-1a, including a bunch of t2.micros I successfully created.
> Does it choose the zone randomly?  How can this be fixed?

Not sure, haven't seen that before.  You can try adding the property

    AvailabilityZone: us-east-1b

to the back end EC2 instance.  To see the list of AZs, run `aws ec2
describe-availability-zones --region us-east-1'.

**Comment by axch** [comment]
stack.yaml now has `AvailabilityZone: !Select [ 1, !GetAZs ]`, which apparently selects the alphabetically second availability zone from the full list.  Is this issue now resolved well enough?
